#!/usr/bin/env python3
from pathlib import Path

from common.multipass import MultipassCtl

HOME_DIR = Path.home()
MULTIPASS_INSTANCE_NAME = "telco-integration"


def main():
    multipass_instance = MultipassCtl(MULTIPASS_INSTANCE_NAME)
    if not multipass_instance.exists():
        multipass_instance.launch()
    multipass_instance.add_mounts()
    multipass_instance.transfer_files()
    multipass_instance.add_ssh_key()


if __name__ == "__main__":
    main()
